VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsScheduledReceiving"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

' 入庫予定データ
Public Id As Long
Public OrderNumber As String      ' 発注番号
Public ProductCode As String      ' 商品コード
Public Quantity As Long           ' 数量
Public DeliveryDate As Date       ' 納期
